In [1]:
import numpy as np

In [2]:
np.array([10,20,30])

array([10, 20, 30])

In [3]:
a = np.array([10, 30, 20, 4, 30])
a[3]

4

In [4]:
a[3:5]

array([ 4, 30])

In [9]:
np.zeros(5)
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [15]:
b = np.array([['x','y','z'],['a','b','c']])
print(type(b))

b.ndim

<class 'numpy.ndarray'>


2

In [23]:
cabeceras = [('nombre','S10'),('edad',int)]
datos = [('Juan',10),('Maria',50),("Alberto",20)]

usuarios = np.array(datos,dtype=cabeceras)

In [24]:
usuarios

array([(b'Juan', 10), (b'Maria', 50), (b'Alberto', 20)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [25]:
np.sort(usuarios,order='nombre')

array([(b'Alberto', 20), (b'Juan', 10), (b'Maria', 50)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [26]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [28]:
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])